apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s" .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ $fullname }}
    com.fyralabs.component: {{ $fullname }}
    com.fyralabs.release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/component: {{ $fullname }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ghost.selectorLabels" . | nindent 8 }}
    spec: {{ $claim := .Values.persistence.existingClaim | default (printf "%s-data" $fullname) }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ghost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: {{ $fullname }}-data
          persistentVolumeClaim: 
            claimName: {{ $claim }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
          - name: {{ $fullname }}-data
            mountPath: /var/lib/ghost/content
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: url
              # turn into string
              value: {{ .Values.url | quote }}
            - name: database__client
              value: {{ .Values.database.client | quote  }}
            - name: database__connection__host
              value: {{ .Values.database.host | quote }}
            - name: database__connection__user
              value: {{ .Values.database.user | quote }}
            - name: database__connection__password
              value: {{ .Values.database.password | quote }}
            - name: database__connection__database
              value: {{ .Values.database.dbname | quote }}

            {{- if .Values.mail.enabled | quote }}
            - name: mail__transport
              value: {{ .Values.mail.transport | quote }}
            - name: mail__from
              value: {{ .Values.mail.from | quote }}
            - name: mail__options__host
              value: {{ .Values.mail.host | quote }}
            - name: mail__options__port
              value: {{ .Values.mail.port | quote }}
            - name: mail__options__auth__user
              value: {{ .Values.mail.auth.user | quote }}
            - name: mail__options__auth__pass
              value: {{ .Values.mail.auth.password | quote }}
            {{- end }}
            - name: NODE_ENV
              value: {{ternary "development" "production" .Values.dev_mode | quote }}

          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
