{{- if .Values.persistence.enabled -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ghost
spec:
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.persistence.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end -}}