---

{{- if and (.Values.persistence.enabled) (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {{ $fullname := printf "%s" .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $fullname }}
    com.fyralabs.component: {{ $fullname }}
    com.fyralabs.release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/component: {{ $fullname }}

spec:
  {{ if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{ else }}
  # for each access modes
  accessModes: {{ .Values.persistence.accessModes }} 
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

{{- end}}