apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: http
    targetPort: 
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}